### ISSUE TITLE
Guidelines overlap X-axis

### ISSUE THREAD

**Issue by vkaramov** [i-schuetz/SwiftCharts#126]
When I made guideline width 0.5, it overlap X-axis.
![screenshot](http://i.piccy.info/i9/0104824d007a7be86ce3189c66ba6dd2/1462447420/14424/1009812/2016_05_05_14_20_05.png)

**Comment by i-schuetz** [comment]
Hmm ok the guidelines layer should skip the locations of the axes. In the meantime, you pass your own subclass of [ChartGuideLinesLayer](https://github.com/i-schuetz/SwiftCharts/blob/master/SwiftCharts/Layers/ChartGuideLinesLayer.swift#L95) and override `chartViewDrawing` to fix this. You can copy the contents of the [original](https://github.com/i-schuetz/SwiftCharts/blob/master/SwiftCharts/Layers/ChartGuideLinesLayer.swift#L55) and adjust it to filter out the location of the axis from `yScreenLocs`. If the fix is good you also can submit a pull request with it!

**Comment by i-schuetz** [comment]
Fixed
