### ISSUE TITLE
Horizontal combined chart with variable bar width?

### ISSUE THREAD

**Issue by Robarelli** [i-schuetz/SwiftCharts#131]
Use case: we have data on a bunch of snow layers at a given site and have measured the depth and thickness of each layer. We also measure temperatures at variable depth levels. See an example [here](http://www.sierraavalanchecenter.org/sites/default/files/2013-12-09-rubicon.jpg) (disregard the data to the right of the chart). As seen in the example, the chart needs to be horizontal to visualize depth and the bars need to be touching and have variable height to represent thickness of the layer as it goes deeper.

I understand this is a unique case, but would this be possible with SwiftCharts in it's current state or in a future release? Can it be extended to achieve such functionality? If not, do you know of any packages that may contain this sort of functionality?

Thanks in advance

**Comment by i-schuetz** [comment]
It's possible. Because of the variable height you can't use the default bars. But you can use a generic `ChartPointsViewsLayer` where you pass a view generator, like here[https://github.com/i-schuetz/SwiftCharts/blob/master/Examples/Examples/HelloWorld.swift#L43](url) which outputs arbitrary views. You just have to map your model data to chart points in such way that the view generator can create the corresponding view, with correct width and height for each bar.

The temperature is straight forward, just a line layer on top of the bars.

I'm also available for hire if you want a finished example :)

**Comment by Robarelli** [comment]
Thanks, i-schuetz! I will play around a bit with your suggestion and will report back if it's able to do the job. I sent you an email regarding the offer, too :)
