### ISSUE TITLE
Question : Multiple ChartPointsLineTrackerLayer

### ISSUE THREAD

**Issue by WoodySlum** [i-schuetz/SwiftCharts#133]
Hi, you done a great job with this lib ! Thank you for sharing

Would it be possible to have multiple ChartPointsLineTrackerLayer (I have multiple lines in my chart) ?
Could I retrieve X/Y values through a protocol ?

**Comment by i-schuetz** [comment]
Hi,

thanks! Mmm, the tracker selects the nearest intersection so I think it's possible to make it work with multiple lines. You'd have to pass the chart points of all the lines concatenated in an order like this:

------------->
<-------------
------------->

Or:

<-------------
------------->
<-------------

Such that the "joining" lines between your lines are at the edges of the chart and will not intersect with the tracker line.

There's no protocol to retrieve the values of the tracker yet. You can use your own layers though, so you can copy the tracker layer and modify it to pass the values to a protocol. The view where the coordinates are shown currently should also be at least optional. If you do this a pull request would be welcome.

**Comment by i-schuetz** [comment]
Hi,

thanks! For lines in the same chart this is not supported though it shouldn't be difficult to modify the layer to do this. First of all, you'd have to pass the chart points from all lines concatenated in one single line, in such way that the "joining" lines appear on the edges and don't intersect with the tracker line. This means the order of the chart points in the lines would be like this:

------------->
<-------------
------------->

Or:

<-------------
------------->
<-------------

Second you'd have to modify the tracker layer to process all the intersections. Currently it [selects the first one](https://github.com/i-schuetz/SwiftCharts/blob/master/SwiftCharts/Layers/ChartPointsLineTrackerLayer.swift#L166). 

The only complication here, is that theoretically you can have multiple intersections with the *same* line (see [this issue](https://github.com/i-schuetz/SwiftCharts/issues/9) - the functionality to select the nearest point was implemented because of this), so either you are sure that you will not have such lines in your chart and use a single line like described above, or you modify the tracker layer to accept an array of lines, and with this can check if the points belong to the same or different lines in order to determine if the intersection has to be processed.

There's no protocol to retrieve the values of the tracker yet. You can use your own layers though, so you can copy the tracker layer and modify it to pass the values to a protocol. The view where the coordinates are shown currently should also be at least optional. If you do this a pull request would be welcome.

There's also [this pull request](https://github.com/i-schuetz/SwiftCharts/pull/124) for multiple lines, but I assume you have them in the same chart.

Feel free to ask again if you get stuck, happy to assist with adding this functionality such that we can merge it in the library later.

**Comment by i-schuetz** [comment]
Any news here? I edited the post and corrected some things, just in case you're reading this only via email.

**Comment by WoodySlum** [comment]
Hi, sorry for late answer.

The lines does not have the same units ; that's why I can't use a single line as you explained above if I well understood.
Can I overload the tracker to manage this ?

**Comment by i-schuetz** [comment]
As I mentioned you can modify the layer instead, which would be actually preferable. You could subclass it but I find it better to do these modifications directly in the current tracker layer and merge this in the library.

**Comment by WoodySlum** [comment]
Ok I'll give a try ! Thank you for your answer, you can close the topic 👍
