### ISSUE TITLE
In bar chart bars are overlapping on X axis line. Is there any solution?

### ISSUE THREAD

**Issue by anismansuri63** [i-schuetz/SwiftCharts#151]
![screen shot 2016-08-06 at 10 39 37 am](https://cloud.githubusercontent.com/assets/16034467/17454826/21e2181a-5bc2-11e6-9d6a-a3e4487f9da1.png)

**Comment by i-schuetz** [comment]
This is a bug. A quick fix would be to add a view on top of the chart that looks like the bottom line such that it covers the bottom of the bars. To do this, create a dummy chart point with y value of 0 (the x value can be anything), a view generator, that creates the line view using the screen location of the chart point (see e.g. hello world example to see how to use the view generator), and create a layer with this which you pass as the last one in the layers array such that it appears on top.

Note that it's not possible to do this trick by simply moving the x axis layer to the last position in the layers, since it uses core graphics to render its context which always appears behind UIViews like the bars.
