### ISSUE TITLE
Bar Labels in Group Bar Chart

### ISSUE THREAD

**Issue by fczelkmaya** [i-schuetz/SwiftCharts#156]
Hi all. I'm using Group Bar Chart and I need to add Bar Label Layer - to display label above each bar. Can somebody help me? How do I find chartPoints for this layer in Group Bar Chart (I am using code form example).

Thank you!

**Comment by i-schuetz** [comment]
Hmm, well, the grouped bars layer currently doesn't have anything to retrieve directly the screen coordinates of the groups and elements. Pull request? :) You can create your own layer as a copy of the grouped bars layers and do the necessary changes.

Other than that, you have already the y-coordinate (in the case of vertical bars, otherwise x) of the bars in the models, which would be the the y coordinate of the chart points, can pass an unused value as x coordinate and, using the index, do the maths based on how many groups you have, your bar width/spacing settings, etc. to calculate the screen x coordinate in the generator. This is is rather ugly workaround though and the best would be to have convenient accessors to retrieve this from the layer.

**Comment by fczelkmaya** [comment]
I tried to create copy of ChartPointsBarGroup with changes but I probably made wrong changes or I'm not sure what exactly should I change. Could you please help me to find what changes should I do? :) Thank you.

**Comment by i-schuetz** [comment]
Just "remembering" the generated groups / bars and offer convenient accessors for things like getting the screen position of the bars, the center of the group. etc.

**Comment by i-schuetz** [comment]
Just for the record, there's now [GroupedBarsCompanionsLayer](https://github.com/i-schuetz/SwiftCharts/blob/master/SwiftCharts/Layers/GroupedBarsCompanionsLayer.swift) which can be used for this.
