### ISSUE TITLE
Scaling the chart based on number of X Values to display

### ISSUE THREAD

**Issue by Trever123** [i-schuetz/SwiftCharts#158]
Hi,

Is there a way to scale the data on the graph so that a given number of pieces of data can be seen?

I have many data points and I am basing my project off of the scrollable example and want to set how many pieces of data can be seen at once.

Currently only 3 can be seen and i want to make the bars thinner and gaps smaller to fit more data on.

![img_1446](https://cloud.githubusercontent.com/assets/1190118/18132431/c122c37c-6f8e-11e6-840d-430429ec3593.jpg)

I want to always be able to see 7 pieces of data at once and then need to scroll to see more

Thanks

**Comment by i-schuetz** [comment]
Sure, the group bars layer has settings to change the bar width and the spacing.

Also there's work for zooming & panning being done in a separate fork which will be available soon. With this you can set a smaller initial zoom level.

**Comment by Trever123** [comment]
Thanks, thats great. 

Sorry to tag this on but is there an easy way to handle clicks on grouped bars? I have seen you discuss using a custom generator and `HandlingView` but is this doable for grouped bars?

**Comment by i-schuetz** [comment]
That's also in the fork ;) https://github.com/grafiti-io/SwiftCharts

**Comment by Trever123** [comment]
Beautiful!

**Comment by Trever123** [comment]
Is it easily doable with a custom generator for now as i tried out that fork and it is currently buggy for me? 
Thanks

**Comment by i-schuetz** [comment]
What exactly is buggy? It should work. Of course you also can use custom generators.

**Comment by Trever123** [comment]
If you load the scroll view example in the fork, it does not scroll for me, i am using similar code to this but for grouped bars and I am now wanting to make them selectable. So trying to determine whether using the fork or using the non-fork and adding this feature myself is best.

I am also having issues with setting the bar width as asked above. This is something that seems to be generated based on `barSpacing` and `groupSpacing` here:

`barWidth = ((groupAvailableLength - ((self.barSpacing ?? 0) * (maxBarCountInGroup - 1))) / CGFloat(maxBarCountInGroup))` 

I have changed this code manually to a specified bar width and the chart still wants to always show 3 groups.

Here is a picture with the barWidth, barSpacing and groupSpacing all set to 1 and the chart still attempts to show only 3 pieces of data. (Full dataset is 12 groups of 3 pieces of data using a scroll view)

![img_1448](https://cloud.githubusercontent.com/assets/1190118/18162008/3758364c-702c-11e6-9d5d-a77864563839.jpg)

**Comment by i-schuetz** [comment]
ahh, don't use the scroll example, since now there's zooming and panning it's not needed and it will be removed - it also doesn't work. Use directly the grouped bars example.

**Comment by Trever123** [comment]
So if i use the grouped bars example in the new fork and add lots of data i will be able to scroll left and right and disable the zoom?

Will i also be able to extend the yAxis and add it as a second chart as you have previously recommended so it looks like the graph is scrolling under the yAxis?

Sorry for all the questions and thanks for all the great help

**Comment by i-schuetz** [comment]
I haven't tested a fixed zoom level but it should work, if it doesn't I'll fix it. You'd have to set the min/max zoom in `ChartSettingsZoomPan` in the chart settings to the same value. The yAxis hack is not necessary anymore.

**Comment by Trever123** [comment]
Thats great thanks, i think my last question is how to specify how many pieces of data appear on the screen at once. I have my 12 pieces of data but they are now all crushed and i only want to be able to see a set number then have to scroll for the rest? Hope this makes sense

**Comment by i-schuetz** [comment]
You have to calculate a fitting zoom level. Keep in mind that the spacing / bar width will we scaled up.

**Comment by Trever123** [comment]
With the tap handler for a grouped bar, is there an easy way to highlight all the bars in that group. I am trying to edit the grouped bar example and using the `viewPoint` variable along with knowing which bar in the group is selected and the bars width, have a highlighted area that covers all the bars (i am not bothered that the bars aren't specifically highlighted, i want a highlighted area that just covered all the bars whenever any of them are selected)

Thanks

**Comment by i-schuetz** [comment]
You can either add functionality to the grouped bars layer to highlight specific bars - so for example I can pass, I want to highlight bar 1 in group 2, bar 1 in group 3, or bar 1,2,3 in group 1, etc (a pull request with this would be great!), to highlight you'd use the already implemented transformers (you can subclass if you need a different effect). OR since you say you don't need to highlight the bars themselves, you also could add a custom layer, and whenever you want to highlight the groups you add views to this layer, e.g. a background view for the selected group. This layer would be a view based layer (like the bars layer, i.e. which adds its items as subviews of the content view) its task would be simply to add subviews at arbitrary positions directly to the content view. This would be also an interesting addition as pull request. Finally, you'd have to ensure that the views added to this layer stay behind the bars - by using `sendSubviewToBack` or similar. An alternative to this, in order to now have to care about order, could be to add all the "highlight" subviews to the custom layer at the beginning but hidden, and when you tap on the group then just look for the view by index and make it visible. The only part where you would have to care about order would be at the beginning, by passing this custom layer behind (i.e. with a smaller index in the layer array) the bars layer.

**Comment by i-schuetz** [comment]
Another interesting possibility for the 2nd approach (highlight areas) would be to create something like a "GroupedBarsHighlightLayer" where you pass all the bar settings or even the bars layer as a parameter, and this layer automatically creates the highlight background views with the correct positions/dimensions. Then you just call method on this layer like highlight(groupIndex: 2).

**Comment by Trever123** [comment]
Hey again,

Think I have found a way to do what i was looking for with the other library now thanks. Just wondering why the fork has a deployment target of iOS 9 instead of 8 on this library? 

Thanks

**Comment by i-schuetz** [comment]
Good for you, finding a ready-to-go solution is always great ;) I'll see if maybe I add this in the future such that other users don't have this limitation. The target should be a mistake, will fix that later.
