### ISSUE TITLE
Line charts with a combination of dashed and normal lines.

### ISSUE THREAD

**Issue by tommanuel** [i-schuetz/SwiftCharts#174]
I would like to plot a line chart using a combination of dashed and straight lines, i.e depending on the x axis values I should be able to determine weather the line should be dashed or not. Is this possible?

I have attached a screenshot of the graph I would like to plot
![screen shot 2016-10-14 at 11 59 34 am](https://cloud.githubusercontent.com/assets/16460622/19377666/b6ee0d82-9205-11e6-8ac3-e54e54d009bc.png)
.

**Comment by i-schuetz** [comment]
You can pass separate lines for each segment with a specific pattern.

**Comment by tommanuel** [comment]
Sorry I couldn't follow. Could explain it a bit.

**Comment by i-schuetz** [comment]
Instead of using one line in your example you'd use 3 - one which goes from 30 until Jul 06, (with dashed pattern), etc. Each of these lines would be represented with a line model. You'd have to split your data accordingly.

Alternatively you can display one single line for everything with the dashed path and "cover" it with not-dashed lines.

**Comment by tommanuel** [comment]
Yeah that should solve my problem. Thanks a lot

**Comment by tommanuel** [comment]
Sorry I couldn't get this done. Suppose I use three line models, how will I make the second line start from Jul 06 (as in the above diagram).
