### ISSUE TITLE
Question: optional axis rendering?

### ISSUE THREAD

**Issue by NachoSoto** [i-schuetz/SwiftCharts#206]
Is there a way to render a chart with just one axis? I see `ChartCoordsSpaceLeftBottomSingleAxis`, `ChartCoordsSpaceLeftTopSingleAxis`, `ChartCoordsSpaceRightBottomSingleAxis`, and `ChartCoordsSpaceRightTopSingleAxis`, but no version with no vertical axis.

It looks like `ChartBarsLayer` requires both axis. Would it be possible to make them optional?

**Comment by i-schuetz** [comment]
You always need the axis, to define the coordinate space, but you can simply not pass it to the chart layers. Then it will not be displayed:

```swift
let chart = Chart(
    frame: chartFrame,
    layers: [
        coordsSpace.xAxis,
//        coordsSpace.yAxis,
    ]
)
```
To remove the reserved space you have to set related spacing settings to 0 and don't pass any text to the axis. In detail:

Set `labelsToAxisSpacingY`, `spacingBetweenAxesY`, `labelsSpacing` and `axisTitleLabelsToLabelsSpacing` to 0. (Just noticed that the later should be specific to each axis, or at least not be used when you don't pass a title - right now this affects also the other axes, though it looks ok. You also can change the value of `leading` to compensate for this).

Don't pass an axis title:
`let yModel = ChartAxisModel(axisValues: yValues, axisTitleLabels: [])`

Finally, use axis labels that don't display text (otherwise the max label width will be reserved). For this you can use this custom class:

```swift
class ChartAxisValueInvisible: ChartAxisValue {
    override var labels: [ChartAxisLabel] {
        return []
    }
}
```

Since you are not displaying the axis values you only have to pass the first and last value.
