### ISSUE TITLE
error trying to build example

### ISSUE THREAD

**Issue by timothyrchew** [i-schuetz/SwiftCharts#211]
Thanks for creating this library. I'm new to swift and struggling to get the example working. 

When I build the project, I get the following error- "shared" is unavailable: Use view controller based solutions where appropriate instead, pointing to three lines different lines. This is one of them in the DetailViewController- "let splitViewController = UIApplication.shared.delegate?.window!!.rootViewController as! UISplitViewController".

How could I fix this? Thanks in advance.

**Comment by i-schuetz** [comment]
Can't reproduce it. Some points:

- If you're using version 0.5, you must use Xcode 8+
- Is this only the example project or do you have other stuff? Are you using Realm? Try updating CocoaPods. Apparently, Realm in combination CocoaPods older than 0.39 can cause this error.
- This is likely not the problem, but mentioning it nevertheless,  it's not possible to access the app delegate from an extension.
- Finally, do a hard clean (delete derived data) and pod update:
```
rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
pod search SwiftCharts
```
Let me know how it goes! If it still doesn't work please provide more details in order to be able to reproduce it.

**Comment by DKalachniuk** [comment]
@timothyrchew have the same issue
quick solution - comment out that rows of code. The example would work

**Comment by i-schuetz** [comment]
@timothyrchew @DKalachniuk could you provide your specs? Xcode version? Are you using an extension?
