### ISSUE TITLE
Whats wrong?

### ISSUE THREAD

**Issue by rolyanos** [i-schuetz/SwiftCharts#223]
I am looking for library for my project, I have tryed to setup this lib for 3 days, and there are no success. I installed chart lib instantly. I asked for help, because I cant even try to work with your lib. 

3 issues in charts "issues asks" ,that mean people asking about it.
You are strange man.

**Comment by i-schuetz** [comment]
I asked you in the other thread for your pod version and you said 1.2.0. This is not the pod version. It's the Swift version. I assume you're using a very old version of SwiftCharts that doesn't have the fix.

So far I'm seeing in the commit history, you should be fine using the Swift 1.2 branch:
```ruby
pod 'SwiftCharts', :git => 'https://github.com/i-schuetz/SwiftCharts.git', :branch => 'swift1.2'
```

But I seriously recommend you upgrade your code base to Swift 2.3+ Nobody uses Swift 1.2 anymore and as mentioned in the readme, this is also not maintained here anymore. I can't even test since my Xcode will not compile Swift 1.2.

**Comment by rolyanos** [comment]
![img_0145](https://cloud.githubusercontent.com/assets/17070078/23092395/9a5dda4a-f5d2-11e6-8de7-ed36678edd6a.PNG)
1.2.0 its current pod version, not swift, I am using latest xcode and swift 3. 
Ok, in mondey I record the video of my steps of installing the library, to finds out wat is wrong.

**Comment by i-schuetz** [comment]
Ok, sorry for misunderstanding. I assumed it was obvious that I was asking about the SwiftCharts (the *pod*) version and not the cocoapods version.

Can you upload the project where you are having these issues to your Github? I'll give it a look.

**Comment by rolyanos** [comment]
Ok, but my macbook in office, I will upload it to github in Monday, thanks for help:)

**Comment by rolyanos** [comment]
https://github.com/rolyanos/newChartTest
Hello, this is my project.

**Comment by i-schuetz** [comment]
The problem is that ExampleDefaults is not a part of SwiftCharts, but of the example project. This is just a helper class to store the shared settings for the examples.

Either simply copy ExampleDefaults into your project, or pass your own fonts and settings.

Besides of this you seem to have copied the example from master, which isn't compatible with `0.5.1`. You have to use the example code from `0.5.1`.

**Comment by rolyanos** [comment]
Ok, I will try to do it, thanks a lot!
