### ISSUE TITLE
Is't possible to make MultiAxis scrollable graph using this?

### ISSUE THREAD

**Issue by Punith1234** [i-schuetz/SwiftCharts#224]
Hi, 

Thanks for such a great library. I would like to know whether it's possible to make multi axis scroll view like this - https://github.com/philackm/Scrollable-GraphView

Cause the above link i sent you supports only single line graph. Is't possible to make like that with multiple linegraphs using this. It'll be great helpful for us

**Comment by i-schuetz** [comment]
What do you exactly mean with "like this"?

You can show a (finite) multi-axis scrollable line chart, yes. You can use master and set an initial zoom value to the chart that produces the desired width. There's a scrollable example in the current release version, but it doesn't perform well with large datasets, because it generates all the labels and guidelines at once.

The animations I see there are not supported though. But can be implemented, with some effort.

If you try it out let me know how it goes. The lines are current re-drawn on each zoom/pan delta so I could imagine performance issues for very large datasets, but this is something we/I can work on to optimize.

**Comment by Punith1234** [comment]
Hi @i-schuetz thanks a lot.. Thank you.. 

But I'm not looking for any animations like that. I'm just looking for scrollable graph view where i can draw multiple lines and scroll at the same.. As you mention we can set it through zoom value. Can you help me out in this. 

I've attached a screen shot .. That's what i needed.. If you can help me that would be really great `
![screen shot 2017-02-19 at 7 06 02 pm](https://cloud.githubusercontent.com/assets/13044958/23102839/92691f84-f6d6-11e6-83e9-58d23d52c580.png)

**Comment by i-schuetz** [comment]
I adjusted [one of the examples](https://github.com/i-schuetz/SwiftCharts/blob/master/Examples/Examples/CustomUnitsExample.swift) to show how to set the initial zoom level / scroll area. Also added some explanations.

To use master, you need this in your podfile:
```ruby
pod 'SwiftCharts', :git => 'https://github.com/i-schuetz/SwiftCharts.git'
```

Let me know how it goes! Happy to continue assisting to get your chart working. The zooming api is still a bit unpolished and it requires sometimes non-obvious steps.

**Comment by Punith1234** [comment]
Hi @i-schuetz  thanks for spending your valuable time spending over my problem.. 

I did try with your example .. and it works like charm .. but i wanted multiple line with dots unfortunately.. now i was able to create one line graph with the link i mentioned you  earlier.. so is it possible to do like that in this also?

**Comment by i-schuetz** [comment]
If you look at the code you'll notice that you can pass an *array* of lines to the line layer:

```swift
let chartPointsLineLayer = ChartPointsLineLayer(xAxis: xAxisLayer.axis, yAxis: yAxisLayer.axis, lineModels: [lineModel], delayInit: true)
```
Fir the dots you should use a `ChartPointsViewsLayer`, which you can copy-paste from [Hello world example](https://github.com/i-schuetz/SwiftCharts/blob/master/Examples/Examples/HelloWorld.swift), and adjust to generate dots  instead of labels.
