### ISSUE TITLE
image instead of text on Y Axis

### ISSUE THREAD

**Issue by Yoooj** [i-schuetz/SwiftCharts#233]
Greetings, 
I was wondering if You can accomplish something like this using SwiftCharts. Any tips?

![y_axis_images](https://cloud.githubusercontent.com/assets/6841336/23892199/ecb7ab16-0899-11e7-80c3-9553910ae387.jpg)

Thanks in advance.

**Comment by i-schuetz** [comment]
Yep, in the current release version this is very easy. You can display these images as if they were chart points. You just have to use a `ChartPointsViewsLayer`, similar to how it's done [here](https://github.com/i-schuetz/SwiftCharts/blob/master/Examples/Examples/HelloWorld.swift#L60). You have to pass chart points that correspond to the locations of the images, e.g. (0, 1), (0, 2), (0, 3), etc. (it doesn't have to match 100% - the location, in this case along the y-axis just serves as guide for you to position the images).

In master it's a bit more complicated, since the inner space is clipped, and if you use zooming and panning (the current release version doesn't support it) you also have to ensure that the images only move along the y axis, i.e. don't move to left or right like it would happen with normal chart points. For all this you can orient with [this example](https://github.com/i-schuetz/SwiftCharts/blob/master/Examples/Examples/RangedAxisExample.swift#L134). It's the one with black background and landscape mode in the readme. You can see at the right side 3 markers, which work exactly like your images. You could try, as a start, to modify this example to display images instead of markers and then pass chart points to their layer that position them at even intervals.

I recommend using master, if you want to use zooming and panning and of course because it's more up to date.

**Comment by Yoooj** [comment]
Solid answer. Thank You very much :)!
