### ISSUE TITLE
Displaying points outside of innerView

### ISSUE THREAD

**Issue by ArturoLee** [i-schuetz/SwiftCharts#244]
It looks like there were some recent changes to chartSettings that messed up my project. In the Multi-chart touch tracking, how do you get the point to not get cutoff near the bottom edges (or any edge)?

In my project I had just increased the bottom/leading/top/trailing settings to make sure the point never gets cuts cutoff. However, with the new update, it now gets cutoff. Can you advise on the solution? I thought it had something to do with the customClipRect setting, but maybe I'm doing it wrong. If we can fix it in the Multi-chart example, I can apply it to my project.

Also related: When my line is touching the bottom (or top) of the chart, part of the thickness of the line is getting cutoff. Not sure if that is related to this issue, but that didn't happen to me before (because adjusting the chartSettings solved it).

**Comment by i-schuetz** [comment]
Hey.

It should be like this a while already, because the content has to be clipped for zooming and panning (otherwise when you zoom everything will be displayed outside of the inner boundaries).

I added a `containerViewUnclipped` to be able to add overlays that can display outside of the chart inner frame... I'm thinking now, also, that in general we probably should disable the clipping when the chart doesn't support zooming and panning. What do you think?

**Comment by ArturoLee** [comment]
So before the recent updates it used to always be unclipped? How does contrainerViewUnclipped work in practice? I'm just not able to figure out what the actual solution is. I don't think there's an example I could follow.

Is there something I have to change here?

                    let containerView = U(frame: chart.containerView.bounds)
                    
                    let point = ChartPointEllipseView(center: chartPointModel.screenLoc, diameter: 12)
                    point.fillColor = tintColor.withAlphaComponent(0.5)
                    containerView.addSubview(point)`

**Comment by i-schuetz** [comment]
It should have stopped working in master since Jan. 23 which is when I merged the zooming and panning.

I [added a setting](https://github.com/i-schuetz/SwiftCharts/blob/master/Examples/Examples/MultiTrackerExample.swift#L90) to disable the clipping.

There's still something incorrect though, when you start tracking the background view of the bottom labels doesn't hide completely the axis labels but this should be easy to fix. I'll give it a look later when I have time again.

**Comment by i-schuetz** [comment]
I forgot. If you want to use multi-tracker with zooming, yes, you'd have to use `containerViewUnclipped`. In [RangedAxisExample](https://github.com/i-schuetz/SwiftCharts/blob/master/Examples/Examples/RangedAxisExample.swift) there's an example for this. The 3 markers on the right side use it. Let me know if you have any questions!

**Comment by ArturoLee** [comment]
Perfect! `chartSettings.clipInnerFrame = false` fixed it for me. You might want to consider setting that as the default. Thanks again!

**Comment by i-schuetz** [comment]
Ok, nice!

I think having it on as default is more suitable as when using zooming and panning, which probably many users will do it would seem broken. And you should be able to enable zooming and panning without having to care about internals like the clipping.

I also thought about coupling it to the zooming and panning, i.e. if `clipToBounds = zoomPan.zoomEnabled`, and having an additional setting `forceClipping` with which you can enable clipping when zooming is disabled. But the current approach seems easier to understand, so I went with it.
