### ISSUE TITLE
Swift 3.1

### ISSUE THREAD

**Issue by ogezue** [i-schuetz/SwiftCharts#247]
Could you make our compiler happy again please? 
![bildschirmfoto 2017-04-05 um 14 52 38](https://cloud.githubusercontent.com/assets/2361031/24706355/a5235520-1a0f-11e7-9367-f22db5213925.png)

**Comment by i-schuetz** [comment]
It's fixed in master. But it may take a while to release, there are still some things to do and I don't have a lot of time currently. I'll try to speed this up.

You of course also can use master:
```ruby
pod 'SwiftCharts', :git => 'https://github.com/i-schuetz/SwiftCharts.git'
```

It requires a little migration work but it's not a lot and at least for conventional charts it should be easy to follow with the examples (not all are updated though).

**Comment by ogezue** [comment]
Cool - thanks for your reply!

**Comment by i-schuetz** [comment]
0.6 was released. This should be solved now.

**Comment by ogezue** [comment]
thank you!
