### ISSUE TITLE
question how to highlight certain points after plotting chart bubble view

### ISSUE THREAD

**Issue by tranvutuan** [i-schuetz/SwiftCharts#262]
Below is my chart and I have a question
<img width="613" alt="screen shot 2017-04-26 at 2 17 01 pm" src="https://cloud.githubusercontent.com/assets/1260360/25449879/2fbfbe22-2a8b-11e7-91d2-84fcb498085a.png">

1. Currently, in order to highlight some bubble points from the chart, I have to redraw the whole chart with pre-coloured points. Is there a way to access to some bubble points from the plotted chart so that I can change the their background colors

**Comment by i-schuetz** [comment]
Which layer are you using to display chart points?

**Comment by tranvutuan** [comment]
I'm currently using ` ChartPointBubble` for the chart point and using ChartPointsViewsLayer like following
```
fileprivate func bubblesLayer(_ xAxisLayer: ChartAxisLayer, yAxisLayer: ChartAxisLayer, chartInnerFrame: CGRect, chartPoints: [ChartPointBubble], diameter: CGFloat) -> ChartLayer {
        
        return ChartPointsViewsLayer(xAxis: xAxisLayer , yAxis: yAxisLayer, innerFrame: frame, chartPoints: chartPoints, viewGenerator: {(chartPointModel, layer, chart) -> UIView? in
            
            let circleView = ChartPointEllipseView(center: chartPointModel.screenLoc, diameter: CGFloat(chartPointModel.chartPoint.diameterScalar) + 3.0)
            circleView.fillColor = chartPointModel.chartPoint.bgColor

            return circleView
        })
   
    }
```

I also notice that, some of my bubble points are not perfectly rounded.

**Comment by i-schuetz** [comment]
Hmm. I'm not sure what causes the circles to be clipped when using corner radius. I may be related with using fractions for the size of the view (does `diameterScalar` return a number with fractions?), as there's sometimes rounding going on that may cause a little part of the underlaying layer to show outside of the view, thus being clipped? Try using whole numbers (round down) or maybe try setting `clipToBounds` of the view to `false`. 

There are also other possible solutions, like [here](http://stackoverflow.com/questions/25551053/cornerradius-with-border-some-glitch-at-border) where the user solved it using `UIBezierPath`. I have read that corner radius is actually bad for performance, so if you find a better (and performant) way to create circles, feel free to submit a pull request! Otherwise you can of course just use your own views in `viewGenerator`.

To modify the color of the items your can access the `viewsWithChartPoints` property of the `ChartPointsViewsLayer`, e.g:

```swift
chartPointsLayer.viewsWithChartPoints[2].view.backgroundColor = UIColor.red
```

**Comment by tranvutuan** [comment]
@i-schuetz: Thanks for you assistance. The way that I improve the shape of the dot is to add `width` to the `circleView `. You are right, corner radius is bad for the performance. UIBezierPath is much better. I can take a look into it to improve it.
 
Also, thanks for bring it up, I dont know why guidelines is overlapping with y axis. What is 0.6. Currently, I'm setting chartSetting like following
```
let chartSettings = ChartSettings()
        
        let coordsSpace = ChartCoordsSpaceLeftBottomSingleAxis(chartSettings: chartSettings, chartFrame: chartFrame, xModel: xModel, yModel: yModel)
        
        let (xAxisLayer, yAxisLayer, innerFrame) = (coordsSpace.xAxis, coordsSpace.yAxis, coordsSpace.chartInnerFrame)
        
        let guidelinesLayerSettings = ChartGuideLinesDottedLayerSettings(linesColor: UIColor.black, linesWidth: 0.5)
        let guidelinesLayer = ChartGuideLinesDottedLayer(xAxis: xAxisLayer, yAxis: yAxisLayer, innerFrame: innerFrame, settings: guidelinesLayerSettings)
        
        let bubbleLayer = bubblesLayer(xAxisLayer, yAxisLayer: yAxisLayer, chartInnerFrame: innerFrame, chartPoints: chartPoints, diameter: 10)
```

**Comment by i-schuetz** [comment]
0.6 is the new version of SwiftCharts, where the guidelines are fixed, and also the `viewsWithChartPoints` was changed to `open` (readonly, but you can change the color of the views with this).

**Comment by tranvutuan** [comment]
I have just edited my previous question. Can you take a look at it again

**Comment by i-schuetz** [comment]
Where did I say that you have to create an optional property for the layer? We haven't even talked about this.

Probably you mean the chart, which has to be an instance property to prevent being released from memory. The layers don't have to. You also don't have to force unwrap the chart anywhere.

Concerning the circles, I made a mistake, looked in the implementation of `ChartPointTextCircleView`, which uses `cornerRadius`, instead of  `ChartPointEllipseView`, which draws the circles using Core Graphics. There's probably something wrong with the calculation of the circle borders, here:

```swift
let circleRect = (CGRect(x: borderOffset, y: borderOffset, width: frame.size.width - (borderOffset * 2), height: frame.size.height - (borderOffset * 2)))
```
Which could be also the rounding issue we already mentioned. It would be probably fixed by simply reducing the size of circleRect but this is not a proper fix without knowing exactly why and how much.

The drawing with Core Graphics is also the reason that you can't change the color of the circles setting the background color. You would have to change `fillColor` instead and call `setNeedsDisplay` to make it redraw.

**Comment by i-schuetz** [comment]
Addition:

Note also that to avoid having to cast the `UIView`s from `ChartPointsViewsLayer` to `ChartPointEllipseView`, in order to set `fillColor`, you have to set the generic parameters and return type of the closure of `ChartPointsViewsLayer` explicitly, like this:
```swift
ChartPointsViewsLayer<ChartPointBubble, ChartPointEllipseView>(xAxis: xAxisLayer.axis, yAxis: yAxisLayer.axis, chartPoints: chartPoints, viewGenerator: {(chartPointModel, layer, chart) -> ChartPointEllipseView? in ...}
```

**Comment by tranvutuan** [comment]
@i-schuetz: thanks for your help again
