### ISSUE TITLE
Issues with Bar Chart View: scaling, gradient layer, thinner bar chart, hide Y axis grid only

### ISSUE THREAD

**Issue by CeceXX** [i-schuetz/SwiftCharts#269]
Hi Ivan and all,

Thanks for making such a handy library – it's very neat. I have been wrapping my head around it to recreate the following design:

![touched](https://user-images.githubusercontent.com/10504710/27603125-69b7825c-5b75-11e7-86c0-38c50be332c2.png)

Here's what I have so far:

![simulator screen shot 27 jun 2017 20 20 35](https://user-images.githubusercontent.com/10504710/27603275-eacafdba-5b75-11e7-817d-4178eed72011.png)

I can't figure out four things:

1. The first bar ("Jan") is thinner than the other ones. Perhaps it's been clipped out by the axis or something?

2. I can't figure out a way to scale the Y axis when the graph is instantiated. I always need to pinch down to reach y = 0. Is there a way to start from 0, 0? I am currently using this code:

`chart?.zoom(scaleX: 2.4, scaleY: 5, anchorX: 0, anchorY: 0)`

3. I don't know why adding a gradient layer to the view bar layer doesn't actually add anything, even if the background color is set to `.clear`.

`let viewBar = ChartPointViewBar(p1: p1, p2: p2, width: barWidth, bgColor: #colorLiteral(red: 0.1725490196, green: 0.6509803922, blue: 1, alpha: 1), settings: settings)
    print("viewBar frame", viewBar.frame)

    let mGradient = CAGradientLayer()
    mGradient.frame = viewBar.bounds
    var colors = [CGColor]()
    colors.append(UIColor(red: 0, green: 0, blue: 0, alpha: 1).cgColor)
    colors.append(UIColor(red: 0, green: 0, blue: 0, alpha: 0).cgColor)

    mGradient.startPoint = CGPoint(x: 0.1, y: 0.5)
    mGradient.endPoint = CGPoint(x: 0.9, y: 0.5)
    mGradient.colors = colors

    viewBar.layer.addSublayer(mGradient)

4. I can't figure out how to hide the X axis grid? Haven't found a way to only hide one of them (not both).

Here's a gist of my view controller:

https://gist.github.com/CeceXX/349d272702be85b7c26fba308c0a6574

Would love some help on this. Thank you!

**Comment by i-schuetz** [comment]
Hi Cesare,

sorry for the delay! A bit busy recently.

To answer your questions:

1. Yes, it's clipped! To prevent this, you can either add a "padding value", similar to how it's done [here](https://github.com/i-schuetz/SwiftCharts/blob/master/SwiftCharts/Convenience/BarsChart.swift#L35), or set a chart padding value as documented [here](https://github.com/i-schuetz/SwiftCharts/wiki/Axes#padding).

2. You have to use 1 instead of 0 as `anchorY` - this is the center of the scaling (in 0..1 range), so if you set it to 0 it will scale from the top of the chart resulting in it being fully scrolled to the end of the y-axis. 

There was a bug here though, which causes `anchorY` to be ignored and I just fixed it. You'd have to use master to get the fix.

3. I honestly don't know the reason (feel free to submit a bug, or maybe investigate it...) but you can also return `UIView` from this function. If you need animation it's also quite easy to do this, using `HandlingView` like in NotificationsExample, among others.

4. To hide a component in the chart you simply have to not pass the corresponding layer to the chart's layers array.

Let me know if this fixes the issues!

**Comment by CeceXX** [comment]
Thanks for your help, Ivan! I will work on your project today and will get back to you if I have any questions :-)

**Comment by CeceXX** [comment]
Hi, Ivan!

I made a few changes to fix points 1, 2, and 4. I have a problem with the one of the labels in the Y axis which is a little bit tilted to the right. Please see the attached image:

![img_7574](https://user-images.githubusercontent.com/10504710/27702011-ed0dccc2-5d02-11e7-9082-2901c1708d3c.PNG)

After I touch the chart/move it around a little bit, everything goes back to normal:

![img_7573](https://user-images.githubusercontent.com/10504710/27701943-bd067cf4-5d02-11e7-8f5f-f504b286a852.PNG)

This is what my x model looks like:

`let xModel = ChartAxisModel(axisValues: xValues, lineColor: .clear, axisTitleLabel: ChartAxisLabel(text: "", settings: labelSettings.defaultVertical()), labelsConflictSolver: nil, leadingPadding: .fixed(13), trailingPadding: .fixed(13), labelSpaceReservationMode: AxisLabelsSpaceReservationMode.current, clipContents: false)`

View controller: https://gist.github.com/CeceXX/918606c58d93bfd7f06f34c1e257c960
ExampleDefaults.swift: https://gist.github.com/CeceXX/cdb797661fbf2070947c7cea4c899181

Really not sure how to go about fixing this and I would appreciate your help. Thanks!

**Comment by i-schuetz** [comment]
Hi Cesare,

I couldn't run your example, because it has a few dependencies which are not attached.

Here's a guess though: Try to set the `labelSpaceReservationMode` of the y-axis to `maxPresentedSize` or `fixed(spaceInPt)`. This prevents recalculating the content frame and label-size related scaling during panning. `current` mode modifies the content frame each time that the max. label size changes, during the gesture, and this (in combination with other things) can lead to an incorrect scaling sometimes (I'll add a note about this to the wiki).

You can also use the same setting for the x-axis. Using `current` for it most of the times doesn't make sense - this would, for example, make the frame change its height when you zoom a lot and don't generate new labels in between (because there are no visible labels, so the content frame expands to occupy that height), causing visible jumps.

If you still have issues, please upload a self contained example...

**Comment by CeceXX** [comment]
Thanks so much Ivan. I will try to fix the padding issues and see what happens.

By the way, I've managed to fix the gradient by using a standard `UIView` instead of the custom subclass `ChartPointViewBar`. 

The last thing I need to figure out is how to add that red "target" line that you see in the first screenshot I've posted above (plus that "Target" text). That should be fairly straightforward, I think, since your charts are layer-based. Need to dig into the wiki a little bit more. Any hints? 

Thanks again for your help!

**Comment by i-schuetz** [comment]
There's a similar line [here](https://github.com/i-schuetz/SwiftCharts/blob/0f25b22c7161c08cf98fe33a8fa904b6eb180475/Examples/Examples/BarsPlusMinusWithGradientExample.swift#L96). You basically have to use a view generator (the same you're using for the bars) and pass a "fake" chart point that acts as a positioning reference. The label can be added in the same way. 

The linked example scales the line with the chart though, which is probably not what you want. To prevent this you have to pass to the layer `. translate` mode, to indicate that you want the view to be only re-positioned. For the label you maybe need `.custom` mode, in case you also want to keep it at a fixed distance from the line. More about this [here](https://github.com/i-schuetz/SwiftCharts/wiki/View-hierarchy-and-transforms#chartpointsviewslayer-transform-modes). You can also find both of these modes in use in some of the examples.

**Comment by CeceXX** [comment]
Hi Ivan,

First off, thanks so much for your help again. I was able to add a red line using a view generation and by passing a fake chart point. I was also able to create a label and add it to the bar chart pretty easily.

The only problem I am now facing is that I don't completely understand how to add a fixed spacing to the red line. I understand that the `mode` should be set to `.custom` and that I need to use a `customTransformer` to give the label some fixed spacing to the line, though I don't know how. In your documentation you use something like this: `lineLayer.modelLocToScreenLoc(x: model.chartPoint.x.scalar` to get a reference to the line label x position, though this doesn't work (aka Budget label disappears and doesn't move along with the red line).

[BarChartTest.zip](https://github.com/i-schuetz/SwiftCharts/files/1130862/BarChartTest.zip)

![simulator screen shot 07 lug 2017 11 57 43](https://user-images.githubusercontent.com/10504710/27956994-866a2e14-631c-11e7-91ef-154344ed6f89.png)

Thanks again,
Cesare

**Comment by CeceXX** [comment]
Hi Ivan, I know you're busy so if you could help me out with the label above the red line I would be so thankful to you. Thank you!

**Comment by i-schuetz** [comment]
Will look in the evening today!

**Comment by i-schuetz** [comment]
Ok, attached an improved version.

To draw the line I replaced the view overlay with a line layer (the same that is used to display a line chart), this is actually better since it handles the scaling (e.g. displays the line with the correct width, in your case) and has also built in animation in case you need it.

For the custom label transformer, I also changed the offset to the screen coordinates, since this is what has to keep unchanged.

You probably should also set the starting zoom level as min zoom level of the chart (this can be done in the chart settings), as it becomes unwieldy when zooming out.

Let me know if this solves the issues!

[BarChartTest 2.zip](https://github.com/i-schuetz/SwiftCharts/files/1149871/BarChartTest.2.zip)

**Comment by CeceXX** [comment]
Thanks so much!! I will get to it asap and let you know how it goes. Do you have any donation link for this library?

**Comment by i-schuetz** [comment]
Ok, looking forward to it.

Re: donation link, good idea! I added one to the readme :)

**Comment by CeceXX** [comment]
Thanks so much for your help again. Please let me offer a beer :-)

Closing this issue 💯

**Comment by i-schuetz** [comment]
Thanks!
