### ISSUE TITLE
Vertical Line Chart Animation

### ISSUE THREAD

**Issue by rejdic** [i-schuetz/SwiftCharts#275]
Is there anyway to make the line chart points animate vertically instead of only horizontally?

Something similar to this:
https://github.com/philackm/ScrollableGraphView/blob/master/readme_images/init_anim_high_fps.gif

Don't need the entire bounce animation, just to have the graph come up from the bottom.

Thanks!

**Comment by i-schuetz** [comment]
It's not built-in but shouldn't be super difficult to add - for a start you could subclass [ChartPointsLineLayer](https://github.com/i-schuetz/SwiftCharts/blob/78c09df3037bc6a2ba9d0f1e327b2b40229352f1/SwiftCharts/Layers/ChartPointsLineLayer.swift).

In particular you're interested in [generateLineView](https://github.com/i-schuetz/SwiftCharts/blob/78c09df3037bc6a2ba9d0f1e327b2b40229352f1/SwiftCharts/Layers/ChartPointsLineLayer.swift#L135) method, which is used when the the line is rendered via views/layers instead of using core graphics. You can return here a view that shows this animation. For this view, you can also subclass / reuse parts of `ChartLinesView`. A good start would be to look at `[generateLayer](https://github.com/i-schuetz/SwiftCharts/blob/57d1a27f3f05663cb6e7656c567f8c5661cddc40/SwiftCharts/Views/ChartLinesView.swift#L56) which is used to show the unmask animation from left to right.

You should be even able to copy the bounce animation from the library you linked to (of course with due credit!).

Finally, you would add a setting to the line layer to specify the type of animation.

Let me know how it goes! I'm interested in having this in the library so happy to help if you want to do a pull request - I'm also available for hire if you want me to implement it for you.

**Comment by rejdic** [comment]
Ok thanks! I will give it a try and let you know.

Also is there any way to update/change the line graph with new data points in real time without having the re render the whole graph?

For example we render the chart with certain cached data points, and once it receives any new data it adjusts the chart automatically most likely moving a couple of data points either up or down depending on what the new data has for those specific points?

**Comment by i-schuetz** [comment]
Dynamic updates is something I want to add but don't find the time... it think this also shouldn't be very difficult to implement (but more difficult than the line animations). 

This would be supported by each layer individually, i.e. it would be possible to implement it only for the line layer without caring about the others. The super class(es) of the line layer would need some changes though, to be able to add and remove chart points.

Real time in which the axis range is changed, i.e. appending points, having the chart scrolling to the last, removing the old points and ensuring this works well with zooming and panning - is not trivial. In any case the possibility to update the dynamically would be a requisite for this.

**Comment by rejdic** [comment]
Ok thanks, will attempt to figure out the best process

**Comment by i-schuetz** [comment]
Ok cool! In case you have any questions about specific steps just post them, happy to help!
