### ISSUE TITLE
Adjust spacing between axis values?

### ISSUE THREAD

**Issue by seenoevo** [i-schuetz/SwiftCharts#283]
I'm currently using a `ChartAxisValueDate` to create my `ChartAxisModel`. However, I'm having an issue where the axis values are too close together if the date values are tightly packed.

Here is what I mean:

![untitled](https://user-images.githubusercontent.com/8109158/28905525-f0f7d23c-77c5-11e7-8ab0-4d52a39c01bf.png)

Is there anything that can be done about this aside from rotating the axis values by x degrees?

**Comment by i-schuetz** [comment]
Yes, you can use some classes from the [axis package](https://github.com/i-schuetz/SwiftCharts/tree/master/SwiftCharts/Axis) like the axis values generators (which are in charge of generating the numeric values to show - in your case the timestamps) or `ChartAxisLabelsConflictSolver` (which runs after the values were generated, mapping them to a new array in which you would remove the overlaps). Theoretically you could use also axis labels generators but these are only aware of the value they represent, so don't know anything about the other values or the axis in general, which would make it a bit tricky.

**Comment by i-schuetz** [comment]
I remembered something: If you have a fixed values array, which seems to be the case, you also can use `ChartAxisValuesGeneratorFixedNonOverlapping`. More about all the generators, including this, in the [wiki](https://github.com/i-schuetz/SwiftCharts/wiki/Axes#generators).

**Comment by i-schuetz** [comment]
Another approach I forgot!

You can also make the bars use regular spacing between them, i.e. ignore the numeric value of the dates. You would map your data to use an incrementing integer (1,2,3...n) as x-value instead of the date and keep the date only as the string to be displayed. There's an [example](https://github.com/i-schuetz/SwiftCharts/blob/master/Examples/Examples/EqualSpacingExample.swift) that demonstrates the general principle (not with dates). Probably [this one](https://github.com/i-schuetz/SwiftCharts/blob/master/Examples/Examples/NotNumericExample.swift#L37) is more useful for you - it uses `ChartAxisValueString` which has an `order` field (the incrementing integer) and an arbitrary label (which in your case would be the formatted date).

**Comment by seenoevo** [comment]
thanks...I resolved it using one of your suggestions
