### ISSUE TITLE
Define xValues without .map method?

### ISSUE THREAD

**Issue by sniis84** [i-schuetz/SwiftCharts#31]
I was trying to define the xAxis and yAxis values using Double values.
I tried using ChartAxisValue but with no luck the numbers do not appear while the chart is presented.
Any idea how to define xValues without using .map, or giving a more detailed explanation?

**Comment by i-schuetz** [comment]
You don't have to use `map`. The chart just needs an array of `ChartAxisValue`. How you generate this array is up to you. The examples use `map` because it makes the code easier to read (this has a performance penalty though, since it iterates over all the array, but it's irrelevant for small datasets).

For Doubles you can use `ChartAxisValueFloat`, where you can pass a formatter. `ChartAxisValue` should not be instantiated directly (this is rather an "abstract class" if you are familiar with the concept). This class doesn't have any information about how to display the double, if it generated labels and you pass e.g. 2.3423422342425 it would show all the decimal digits and that's probably not what you want.

**Comment by sniis84** [comment]
var xValues : [ChartAxisValue] = []
    for i in 0..<X.count {
      let val = ChartAxisValueFloat(X[i], labelSettings: labelSettings)
      xValues.append(val)
    }

I've already tried and this provides an error seems that these classes cannot process Doubles if not when using ChartAxisValue(scalar:)

**Comment by sniis84** [comment]
I've tried several times but your example helped me figuring out that a CGFloat is needed by the library.
I just had to use CGFloat(X[i]) in my code to solve it.
I suggest to add documentation about that in the method definition while the use types in the commands

**Comment by i-schuetz** [comment]
Actually, you have a point - there's no real reason to use `CGFloat` here. Somebody changed recently the internal representation to `Double` (because `CGFloat` causes problems with dates), so it's converted to `Double` anyways. It makes sense to replace `ChartAxisValueFloat` with `ChartAxisValueDouble`. I'll leave this open as an enhancement issue.

**Comment by i-schuetz** [comment]
Improvements implemented
