### ISSUE TITLE
Display one data point for Custom Units Scrollable graph

### ISSUE THREAD

**Issue by zoufishanmehdi** [i-schuetz/SwiftCharts#326]
Hi, I would like to display one data point for Custom Units Scrollable graph (Custom Units Example). Is it possible to do it with this library? I  have looked into issues and the library to check and I only see `[ChartAxisValue]` array to create ChartAxisModel (i.e. xModel an yModel), no function to only add one ChartAxisValue for each. Would really appreciate your input. Thank you!

**Comment by i-schuetz** [comment]
Well, the axes need a range - if you just want to use one value, pass 2 additional values as fillers - one at the start and another at the end, such that your value appears centered in the middle. The values of those fillers are not important, as long as they are respectively smaller and bigger than your center value, by the same amount. And make them hidden, such that the labels will not appear on the axis. This is also possible using [generators](https://github.com/i-schuetz/SwiftCharts/wiki/View-hierarchy-and-transforms#chartpointsviewslayer-transform-modes) instead of arrays.

**Comment by i-schuetz** [comment]
Well, the axes need a range - if you just want to use one value, pass 2 additional values as fillers - one at the start and another at the end, such that your value appears centered in the middle. The values of those fillers are not important, as long as they are respectively smaller and bigger than your center value, by the same amount. And make them hidden, such that the labels will not appear on the axis. This is also possible using [generators](https://github.com/i-schuetz/SwiftCharts/wiki/View-hierarchy-and-transforms#chartpointsviewslayer-transform-modes) instead of arrays.

Sorry for the late response, but also, as stated in the placeholders, this kind of questions is better suited for stack overflow!
