### ISSUE TITLE
Tooltip for bars 

### ISSUE THREAD

**Issue by moushumis** [i-schuetz/SwiftCharts#337]
Hi, I have been trying to add tooltips on tap to each bars on a horizontal barchart, that is not stacked. I have not been able to understand how to do this. PLease help me.

I know we can assign a taphandler to the ChartBarsLayer, but it takes a single taphandler and if I try to create a taphandler like let tapHandler = ChartTappedBar(....), it takes a single BarModel object. But I want to add the tooltip to each barModel. I am totally at a deadend. I have been working on this for days, but I have not been able to find a solution.

The thing that I am trying to do is : For each bar in the bar chart, I want to show a label that appears as a tooltip, when that bar is tapped.

**Comment by AAChartModel** [comment]
@moushumis  Maybe AAChartKit-Swift can help you 
 ## https://github.com/AAChartModel/AAChartKit

> AAChartKit-Swift is the Swift language version of AAChartKit which is object-oriented, a set of easy-to-use, extremely elegant graphics drawing controls,based on the popular open source front-end chart library Highcharts. It makes it very fast to add interactive charts to your mobile projects. It supports single touch-drag for data inspection, multi-touch for zooming, and advanced responsiveness for your apps .

**Comment by i-schuetz** [comment]
@AAChartModel 

I don't think that the issues of a library is a suitable place to advertise for another library. Under certain circumstances this may be valuable for the user, just as an ad may be of use for someone browsing a webpage, but this is in general spammy and not welcome. Add links to your library in a central place where users can compare and make an informed decision, but please not here. Thanks.

@moushumis 

I'll take a look at your issue later today, for now in general - of course it's possible to show a tooltip per bar, you should get all the data you need to show the tooltip from the tap handler closure.

**Comment by moushumis** [comment]
@AAChartModel 
Thank you, but I'm in no position to switch to a different library right now. 

@i-schuetz 

Thank you so much for responding. Actually, I noticed the fact that we can pass a tapHandler of the type ChartTappedBar to the ChartBarsLayer. The ChartTappedBar is a struct that looks like this:

public struct ChartTappedBar {
    public let model: ChartBarModel
    public let view: ChartPointViewBar
    public let layer: ChartCoordsSpaceLayer
}

So we can pass only a single ChartBarModel, but I have an array of ChartBarModel. 

Where and how should we declare the tapHandler closure?

Should it be something like: 
let tapHandler = ChartTappedBar(model: barsModel[ i ], view: barsLayer. barViews[ i ].view, layer: chartCoordsSpaceLayer){
   // Set tap handler here..

// I tried this within a for loop through my array of ChartBarModel, but I got a null pointer exception for trying to do: barsLayer. barViews[ i ].view
}

or 

let barViewSettings = ChartBarViewSettings(animDuration: 0.5, selectionViewUpdater: ChartViewSelectorBrightness(selectedFactor: 0.5))
                let barsLayer = ChartBarsLayer(xAxis: xAxisLayer.axis, yAxis: yAxisLayer.axis, bars: bars, horizontal: true, barWidth: Env.iPad ? 40 : 16, settings: barViewSettings){ tappedBar in
....// set tap handler here

// When I try to do this, it tells me that I need to return an object of ChartBarViewPoint..

}

These are the various approaches I have tried so far. My current implementation is very similar to the [bar with dynamic gradient example](https://github.com/i-schuetz/SwiftCharts/blob/master/Examples/Examples/BarsPlusMinusWithGradientExample.swift). 

Thanks once again.

**Comment by i-schuetz** [comment]
@moushumis the closure is not of type `ChartTappedBar`. That's the type of the parameter of the closure! The _library_ passes `ChartTappedBar` to you - not the other way around. In the closure, then, you can do things with the passed `ChartTappedBar` - which is a representation of the bar that was just tapped.

So your first approach doesn't work, because you're trying to pass a `ChartTappedBar` to something that is `((ChartTappedBar) -> Void)`. I believe the declaration of `ChartTappedBar` shouldn't even compile, as you're passing a closure to it as well, which it doesn't expect.

The second approach doesn't work, because you're using trailing closure syntax, this would work if `tapHandler` was the last parameter from the initializer, but there's another after it, which is as well a closure, so the compiler thinks that you're passing that other closure instead of the tap handler. The solution, here, is that you don't use trailing closure syntax.

I recommend getting more familiar with the programming language first, this is all basic things not related with the library.

**Comment by i-schuetz** [comment]
Of course, you have a tap handler will all the bar's data... the rest is left as an exercise!
