### ISSUE TITLE
Issue concerning layers (I think)

### ISSUE THREAD

**Issue by camill-a** [i-schuetz/SwiftCharts#35]
This issue is more a problem of mine I think, but after many spent time i cannot still figure it out...

Why does this code (rougthly the same as the tracker example one) doesn't display anything else than the curve?

http://imgur.com/Gca5Bxf

The datepicker bug is something else, sorry for it. but only the red plot appears. (i tryed on other circumstances before with full view on the curve)

http://imgur.com/UnmfVaO

It may be trivial but I can't find a logical explanation/solution...

**Comment by i-schuetz** [comment]
Can you please provide the code as text (e.g. a gist)?

**Comment by camill-a** [comment]
Here a pastebin, and yhea that's what i though with the view. How can the view influence this, do you have more details? http://pastebin.com/V9zKnL7N

It's not the direct example, but it's really close, and i don't think there are any big errors, must be the view. Is it possible to resize the graphic so it doesnt take full view space? Or may it be what precisely make it crash?

Thanks for your answer

**Comment by i-schuetz** [comment]
The snippets are still missing the context... Is your view's size already computed when you call getChartFrame? Somebody who was using autolayout had similar issues, see https://github.com/i-schuetz/SwiftCharts/issues/30 here the solution: https://gist.github.com/i-schuetz/f6e285eb0c86bb831510

Otherwise start with one of the examples and edit it until you can reproduce it, so we know what exactly is causing the issue. If nothing helps please either post the full code, or upload somewhere a project where the issue is reproduced and I'll take a look.

**Comment by camill-a** [comment]
I think it's on my side, let me spend more time on it before sharing it. Thanks a lot anyway. I keep this open and keep you updated

**Comment by camill-a** [comment]
I am becoming crazy... I don't understand why it won't work. I can use the simplest example, yet I never saw any x or y axis bars. My project is on github, files PowermonitorIOS/viewcontrollers/ChartVC.swift, if you wanna check. I reinstalled SwiftCharts, I deleted my files and recreated them. I don't know what to do

**Comment by i-schuetz** [comment]
The chart has to be referenced, otherwise it's released, and when `ChartBaseView` calls `drawRect` on it (which is used to draw the axes) the reference is nil. `ChartBaseView` doesn't have a strong reference to `Chart` because otherwise it would cause a reference cycle...

This is also why there's an "arc" comment next to the chart declaration in the examples.

This is admittedly a bit cumbersome, may change the architecture in the future to prevent it. A possibility would be to implement the chart directly as view, which is always retained. Right now I'm not sure though if this works nicely with the way the library is designed.

Sorry for not thinking about this before, I actually also had this issue before adding the instance variables, but totally forgot.

**Comment by camill-a** [comment]
It's totally fine, you just share you API and I should check everything more carefully. Anyway, thanks for SwiftCharts! It's great
