### ISSUE TITLE
Tracker Layer Displays NaN for Y

### ISSUE THREAD

**Issue by bsqdev** [i-schuetz/SwiftCharts#41]
Tracker view displays NaN for Y when Y values have a small delta.

Y Values = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 0, 2.008, 2.014, 1.512, 2.016, 0]

X Values can be anything.

![untitled](https://cloud.githubusercontent.com/assets/3995464/9962135/e2bba182-5de9-11e5-8290-6e903059fee6.png)

**Comment by i-schuetz** [comment]
Fixed. The problem was the constant y-coordinate values (horizontal lines), not the small variations.

It's now in master. Note that master is now Swift 2.0. The previous master is now swift1.2 branch (this will not be maintained anymore). Master is safe to use until the next version is released.

Sorry for the long delay, been busy these days.
