### ISSUE TITLE
Documentation is nonexistent 

### ISSUE THREAD

**Issue by opswhisperer** [i-schuetz/SwiftCharts#46]
How soon is "coming soon" for the documentation? Just in line comments in the examples would help. Having a terrible time getting the views sized correctly. In the examples you're moving the view down by 70px why? Using almost identical code my bar chart is squished into about 100px height. Its hard to figure out why without some documentation

**Comment by i-schuetz** [comment]
Hi,
correct, there's litte documentation. On the other side there are a lot of examples and I tried to write the code such that it's self explanatory... but you're right, it needs better docs.

I don't remember why the origin of the frame is 70pt in the demos, but this doesn't matter, this is only the frame of the view and you can change it to whatever you need. Not related with the library itself. If you need autolayout, you can look here https://gist.github.com/i-schuetz/f6e285eb0c86bb831510

I'll be improving the inline documentation gradually, starting in 1 week or so. When that's finished will do the wiki also.

**Comment by opswhisperer** [comment]
I'll check it out, thanks. I can usually deconstruct examples pretty well, this one is just giving me a hard time. Love what I see though, if I can get it working.

**Comment by creisterer-db** [comment]
@opswhisperer are you using the Swift 2.0 branch on Xcode 7? Because I started having the same problem when I pulled in recent updates, where my chart is squished into a small area ~100px height. Chart Frame is fine but the chartInnerFrame returned from calculating coordinate space seems wrong. Haven't dug into it yet but thought I'd mention it since you may be experiencing something similar.

**Comment by opswhisperer** [comment]
Probably not, I'll check. I added it via Cocoapods so I probably got master. Thanks for the tip

**Comment by i-schuetz** [comment]
Master is now Swift 2. There's a new branch for Swift 1.2. Cocoapods from v. 0.3 is Swift 2. Everything is in the readme. The swift2.0 branch still exists but will be removed soon, since it's now in master.

I tested master a few days ago and didn't see any issues. Feel free to open an issue with instructions to reproduce it and I'll give it a look.

**Comment by opswhisperer** [comment]
bummer that gist is not for bar charts. I'm using the generator from the bar chart example but not having any luck.

**Comment by i-schuetz** [comment]
As I said, your problem is not related with the chart but only the UIView, so the gist can be used for any chart. Of course you have to replace the chart's contents. My general approach would be to start with an empty UIView, confirm it has the correct size, then use this for chart. It has to work also without autolayout. If there's an issue please submit a report or upload a project where it can be reproduced and I'll take a look.

**Comment by opswhisperer** [comment]
I think I have this working now. My problem was using too much of the example code. I used all of ExampleDefaults, initially so nothing would break. Its that 70px adjustment that was throwing me off.  The   defaults function moved the view down by 70 and also reduced its height by 70. 

When I don't make that adjustment the chart is indeed 70 above my views frame, I couldn't tell you why exactly. The only change I made was *not* to reduce the height, only move the frame down.

Now I have  completely different problem where all my x axis labels are stacked up near 0,0 in the chart. I'll make a new question for that if I can't figure it out. Thanks for the help.

**Comment by skrite** [comment]
is there an option to put a band marking a specific range in a line chart?  for example, if i have a graph that scales from 0 - 100, could I highlight 20-24 somehow?  Also, do these line charts support a date-time scale for the x-axis ?  Thanks

**Comment by i-schuetz** [comment]
Can you please open a new issue? It's entirely unrelated with this.

**Comment by skrite** [comment]
sorry, i am kinda new here.
