### ISSUE TITLE
Linking touch event on BubbleView to DetailView

### ISSUE THREAD

**Issue by mac389** [i-schuetz/SwiftCharts#5]
It is great that the user can click on a point in the scatter plot and receive more information. 

How would I enable the user to navigate to a detail page that contains further information about the point? 

I envision a storyboard that begins with a tab control. One tab takes the user to the scatter plot. The other tab takes the user through a master-detail sequence. This way the user can access the further detail about the points by scrolling through a tabulation of the points or by clicking them on the screen. 

I know that one would have to link DetailViewController with the viewGenerator for the scatter plot. I'm not sure where to put that linkage in the ViewController for the scatter plot. 

Thanks

**Comment by i-schuetz** [comment]
What you describe is 2x a master-detail structure (in one case the master is the chart and in the other, a tableview). In the case of the chart, if you work with storyboards, you have to set up master detail manually and trigger the segue programmatically, in the touch handler.

You should be able to find plenty of information about how to set up master detail for these cases in internet. There's nothing really chart specific here.

What's maybe worth mentioning from chart side is that in the touch handler (as long as it's defined inside the view generator) you have all the necessary data for your detail controller. The chartPointModel has also an index variable with you can use to look up your original model object. You would have to store it in an instance variable in order to retrieve it in prepareForSegue to pass it to the detail controller.
