### ISSUE TITLE
Scrolling: Using a UIScrollView makes the y-Axis disappear

### ISSUE THREAD

**Issue by henrik-d** [i-schuetz/SwiftCharts#59]
Hey,

first of all, thanks for the library!

I have a question on scrolling. In the examples scrolling is enabled through a UIScrollView which contains the hole chart-view. That way the y-axis isn't visible any more when the user scrolls.

Would it be possible to implement that the axis stay visible? Could you describe which steps would be required to take (high level), then I would try :)

**Comment by i-schuetz** [comment]
You can create a second chart with only the y axis and remove it from the original chart. And add the view of this chart on top of the original chart.

I tried the steps myself because I wanted to confirm it works, so you get the code ;)

```swift
let chart = Chart(
    frame: chartFrame,
    layers: [
        xAxis,
        // removed yAxis
        guidelinesLayer,
        chartPointsLineLayer
    ]
)
// add another chart with only yAxis
let axisChart = Chart(
    frame: CGRectMake(0, 70, yAxis.rect.width + ExamplesDefaults.chartSettings.leading, yAxis.rect.height + ExamplesDefaults.chartSettings.top + 7), // 7 is such that the first axis label is not cut at the bottom
    layers: [
        yAxis
    ]
)
scrollView.addSubview(chart.view)
self.view.addSubview(scrollView)
axisChart.view.backgroundColor = UIColor.whiteColor() // opaque background such that we don't see the scrollview's contents behind
self.view.addSubview(axisChart.view) // axisChart view is now over scrollview and will not scroll
self.axisChart = axisChart
self.chart = chart
```
There's one little issue though with the x-axis labels, as you see the axisChart frame doesn't cover the bottom and you will see the x labels scrolling below it. The reason is if it does it would cut the first x-axis label. One possible solution is to not show a label at the origin of x-axis, then you can set the height of axisChart to cover also the bottom.

**Comment by henrik-d** [comment]
Wow, what a simple but effective solution. Works like a charm! 
Thank you very much.
