### ISSUE TITLE
Updating data

### ISSUE THREAD

**Issue by henrik-d** [i-schuetz/SwiftCharts#61]
Hey,

what is the recommended way to update an existing chart (delete, update or insert values)? Is there anything better than recreate the hole chart?

 Many thanks!

**Comment by i-schuetz** [comment]
Hi,
copying an answer I wrote somewhere else:
The charts right now are for the most part immutable. There's a room for modifications by adding/removing views in view generators. You can for example request at any moment the screen location for chart points and add views at these locations, or store the generated views somewhere and remove them selectively. (...). The library could be modified to be mutable quite easily I think, I never did because I didn't need it. If you feel like it you could give that a try. E.g. make the 'let' holding the chart points a 'var', and add an 'addChartPoint' method, which triggers the view generator for the added chart point.. and ensure that the view is added behind views of possible layers in front of it.

**Comment by eklektek** [comment]
Some time has past since December 2015 - are there are any plans to provide support for Updating data?

**Comment by i-schuetz** [comment]
@eklektek I don't have time to add new features. I only do upgrades and merge pull requests. This is unlikely to change soon. If someone does a PR I'm happy to give it a look.
