### ISSUE TITLE
How to highlight cirlce in Show touch coords example?

### ISSUE THREAD

**Issue by christinalau** [i-schuetz/SwiftCharts#66]
Hi, in the Show touch coords (interactive) example, how can I make the circle highlighted (i.e. selected) when there is a selection? Right now it is showing the line and co-ord but I just want the circle highlighted instead (to keep it simple).

I noticed that in Areas,line,circles example, the circle is highlighted but I didn't want to have text inside.

So I am a little unsure what classes to use to accomplish the simple scenario. Thanks a lot for your help.

**Comment by i-schuetz** [comment]
I think you can adjust the [circleViewGenerator](https://github.com/i-schuetz/SwiftCharts/blob/master/Examples/Examples/CoordsExample.swift#L77) to handle the touches itself. You can pass a touchHandler block to ChartPointEllipseView. In this handler you would have access to ChartPointEllipseView to change its colors. Then you also don't need the [touchViewsGenerator](https://github.com/i-schuetz/SwiftCharts/blob/master/Examples/Examples/CoordsExample.swift#L61). 

I'm not sure if the tap area of ChartPointEllipseView will be sufficient, if not you could return a HandlingView in circleViewGenerator (instead of ChartPointEllipseView) with a slightly bigger area than the circles. You would add then ChartPointEllipseView as a subview of this bigger view.

**Comment by christinalau** [comment]
Thanks, can you share the snippet of code? I tried to add circleView.touchHandler to the circleViewGenerator, but it does not get call at all. Thanks again...

**Comment by i-schuetz** [comment]
Did you inspect the view hierarchy? Maybe there's something on top of the views consuming the touch. Maybe it also needs to set userInteractionEnabled. If this doesn't help please post your code to find the problem.

**Comment by christinalau** [comment]
The userInteractionEnabled seems to solve the original problem, now the touchHandler is called. However, I am unable to change the color:

let circleViewGenerator = {(chartPointModel: ChartPointLayerModel, layer: ChartPointsLayer, chart: Chart) -> UIView? in
            
            let circleView = ChartPointEllipseView(center: chartPointModel.screenLoc, diameter: 24)
            
            circleView.touchHandler = {
                print("@@@@ **** touch circle..")
                circleView.fillColor = UIColor.redColor()
                circleView.borderColor = UIColor.greenColor()
                circleView.animDuration = 1.5
            
            }
            circleView.userInteractionEnabled = true
            circleView.animDuration = 1.5
            circleView.fillColor = UIColor.whiteColor()
            circleView.borderWidth = 5
            circleView.borderColor = UIColor.blueColor()
                        
            return circleView
        }

Is this correct or am I missing something? Thanks... I also need a way to clear the previous selection and is uncertain about the approach...

**Comment by i-schuetz** [comment]
Yes, it's correct, you only have to add `circleView.setNeedsDisplay()` after the color changes. In order to clear the selection you can use the same approach from AreasExample, just store the last selection in a variable and reset the colors when you select a new one.

**Comment by christinalau** [comment]
Thanks, works perfectly :+1:

**Comment by i-schuetz** [comment]
You're welcome!
