### ISSUE TITLE
Clarify usage of protocols and classes in implementation

### ISSUE THREAD

**Issue by interstateone** [i-schuetz/SwiftCharts#73]
I've been working on doing this myself, but I've come to a point where I think it would be helpful for you to provide some input as to where this should go.

An example of what I mean: There is a ChartLayer protocol for conforming types to be able to draw in a chart's context. There is then a single ChartLayerBase base class that implements this protocol with empty methods for subclasses to override if necessary. This seems like a mixture of two different concepts that ends up negating any potential benefits of either. I.e. Anything that would implement the protocol probably will end up just subclassing the base class, and any of the benefits of using protocols instead of inheritance is lost. The situation with ChartAxisLayer is similar.

In investigating alternatives, I found that when mixing protocols with default implementations and class inheritance, the rulers for which method implementation gets called is a little different than what one might think, and so a simple change ends up not working.

Instead I'd propose using protocols strictly for describing a defined set of behaviour of a type instead of a particular component of a chart. For example: the ChartLayer protocol could be renamed to DrawableLayer, have empty default implementations of its methods, and the different kinds of components of a chart (`ChartAxisLayer`, `ChartCoordsSpaceLayer`, etc. and their subclasses) would each implement this protocol. This would also involve removing the `ChartAxisLayer` protocol in favour of the existing `ChartAxisLayerDefault` base class.

I've gotten this far on a branch of SwiftCharts, and then I noticed that there is also a `ChartContextDrawer` base class that looks a lot like my new `DrawableLayer` protocol. So I think this is where I need input from you! Although there might be a difference between the kinds of chart components that conform to/subclass `ChartLayer` and `ChartContextDrawer`, the two interfaces are almost exactly the same and I think they should be one and the same or at least more closely related. Is there a reason that these were separate before?

Example, where these could also be a single protocol:
```swift
protocol Drawable {
    func initialize(chart: Chart)
    func draw(context: CGContextRef, chart: Chart)
}

protocol Hideable: Drawable {
    var hidden: Bool { get, set }
}

extension Hideable {
    func drawIfVisible(context: CGContextRef, chart: Chart) {
        if !hidden {
            draw(context: context, chart: chart)
        }
    }
}
```

**Comment by i-schuetz** [comment]
Using protocol extensions would be a great, I didn't do this because at the time I wrote the library it was not possible to use them for this. `ChartLayerBase` is there only to not make layer subclasses implement both methods (similar to adapter class in Java) as in most cases they'll implement either one or the other... I could have also declared the protocol method as optional (with objc annotation) but ended deciding for adapter class. Using a protocol extension to provide  empty implementations is a good idea. 

Concerning behaviour, it may be worth considering if for the methods in ChartLayer 2 protocols are needed instead of 1, since they correspond to use cases that are usually mutually exclusive (don't have to though). `chartViewDrawing` is used to render to the context of the chart view, and `chartInitialized` to add subviews to it. Everything that is drawn using `chartViewDrawing`, will appear behind views that are added using `chartInitialized`, independently of layer. Thus it's unlikely someone would want to combine them in the same layer, if it's needed to render to view context there's always the possibility to do this in the added subviews also. Maybe having 2 different protocols can help making this separation clearer, on the other side this would mean we would have to pass 2 different layer arrays to `Chart` which makes the interface a bit more complex. Nevertheless it would be a more realistic realistic representation of the drawing stack, where basically all core graphics layers are at the bottom then all the views on top of it. I'd probably just let them in one protocol, but you can think about it. "DrawableLayer" in any case emphasises the "rendering" aspect and makes adding subviews in `chartInitialized` look a bit like an unplanned side effect.

The reasoning behind `ChartAxisLayer` and `ChartAxisLayerDefault` was different, here the default class does some decisions about how to render the axis, like rendering the line and labels using core graphics. Maybe someone wants to use subviews instead, e.g. to add animations or effects, in which case they'd create a new implementation of the protocol.

About `ChartContextDrawer`, the reason I did this separate to the layers is that this is conceptually not a layer, just a helper component that can be used by layers, to draw using core graphics. This connects with what I said about the `ChartLayer` methods, we could have a generic "ChartDrawable", which would be implemented by some layers as well as these components, the question would be how this would be integrated this with the existing layer system.

**Comment by interstateone** [comment]
Thanks for the info @i-schuetz! I think this clears things up. Separating drawing and "subview-hosting" like you mentioned could be a good solution here. As an example, if there was a Drawable protocol exclusively for drawing (LineDrawer, LabelDrawer, etc.) then a Layer protocol would inherit from Drawable. I'm mostly repeating what you already said back to you :smile:. I'll poke around and see how this works out and report back.

As for the axis layer case, this makes more sense now too, but perhaps the name of the default class could be "ChartAxisDrawerLayer" (or something else) to distinguish it as _a possible_ default implementation that handles the common use case as opposed to _the_ default implementation that someone should use if they're going to subclass. Documentation of the class may help make this clear too.

**Comment by i-schuetz** [comment]
I know classes meant to be subclassed rather prefixed with "Base", but yeah, "Default" is not really definitive of the class itself, rather how it's used and you're right that this should not be in the class name. "ChartAxisDrawerLayer" or similar is good :)
