### ISSUE TITLE
Fixed width / height coordinate space ?

### ISSUE THREAD

**Issue by meyumeapps** [i-schuetz/SwiftCharts#81]
Hi,

I have several charts which I'm showing one after the other in the same view.

I'm finding that the width of the chart varies between each one and I think i've tracked it down to the coordinate space calculator.

I don't mind the width of the bars etc being different between charts but I'm trying to achieve the inner frame CGRect to be the same across the different charts. So as the user swipes left/right to reveal the charts they have the same left/right margins and the left/right Y axis appear in the same positions.

Any help is much appreciated.
Thanks
Scott Wilson-Billing

**Comment by i-schuetz** [comment]
Hi Scott,

the innerframe is calculated using mostly static data (margins, spacing passed in settings) and the size of the axis labels - more exactly the max. label width in case of y-axis, and max height in case of x-axis.

To keep the inner frame constant, you can either create the axis layers and the inner frame manually instead of using `ChartCoordsSpace` (for this I'd recommend orienting with the code in `ChartCoordsSpace`). Of course these static screen coordinates may cause some labels to be cut, so you have to use frames that ensure all the charts are displayed correctly.

Or (easier, I think) you can add somewhere in all charts a label containing only empty text, which has the max. text length from all the charts (in the corresponding axis - your problem is probably `y` I think). This would hinder the variations of the shorter labels to affect the inner frame. You have to take care that this invisible label doesn't affect e.g. the guidelines, that is to pass it only to the axis. Or reuse an axis value, 0 for example - which is frequently not shown when it's in the bottom left corner.

**Comment by meyumeapps** [comment]
Thanks Ivan, yes, I think my problem is caused by the high x axis and affects the widths of the chart. I will try your idea of the long empty text label.

**Comment by meyumeapps** [comment]
Hi Ivan,

I think i've narrowed the issue down to the labels on the Y axis.

E.g. 

Chart 1 Y Axis
47.98
53.25
etc

Chart 2 Y Axis
4
6
7
etc

So, I believe the wider labels between chart 1 and chart 2 means the edges don't align in the X position.

However, the weird thing is I don't include the Y Axis in my chart layers - I'm not interested in showing these labels.

It seems that the coordinate space calculator still includes the Y axis in the calculations regardless.

I noticed that a chart axis label has a hidden property? Although I can't see this referenced in the coordinate space calculator either.

Any thoughts on a simple solution for my issue please?
Thanks
Scott

**Comment by i-schuetz** [comment]
Hi Scott,

this is what I told you and the solutions are also what I described. The hidden property unfortunately as you say don't exclude the size of the calculation and not showing the axis also does't affect the inner frame. There's some room for improvement here.

Now if you don't show the y axis, then there's a more simple solution indeed, just use axis values that return no labels, this way the width is constant. For this you can simply use a local class that extends the axis values class that you're using and returns an empty labels array.

**Comment by meyumeapps** [comment]
Thanks Ivan, you were spot on :)

I added this to my base chart class and whenever I want empty labels I just use it.

```
class ChartAxisValueEmptyLabel: ChartAxisValueDouble {
    
    init(value: Double) {
        super.init(value)
    }
    
    override var labels:[ChartAxisLabel] {
        return []
    }
}

```

**Comment by i-schuetz** [comment]
Nice!
