### ISSUE TITLE
issues positioning center labels and offsets

### ISSUE THREAD

**Issue by robomotic** [i-schuetz/SwiftCharts#96]
Hello guys,
I have one issue and one question for positioning labels in my graph.
When I rotate my labels with the .defaultVertical method of ChartLabelSettings, the labels are place with an offset from the center point. 
How do I make sure they are properly aligned with the data points?

Also I would like to offset the y labels on the right of the vertical axis e.g. to put them inside the plot area in an attempt to save some space.
How do I achieve that?

I have looked at the demo code, but those cases are not included .
Any help is welcome!

![simulator screen shot 1 mar 2016 23 44 28](https://cloud.githubusercontent.com/assets/315964/13445966/926e50b2-e007-11e5-8cd9-722ec62cf75d.png)

**Comment by i-schuetz** [comment]
Hi,
couldn't reproduce the alignment problem. Please make sure that `rotationKeep` in the label settings is set to `.Top`. I tested with [NotNumericExample](https://github.com/i-schuetz/SwiftCharts/blob/bd1d5b3f63f7c524004604708ccad9bcd84dd693/Examples/Examples/NotNumericExample.swift#L36) where I changed the rotation to -90 and it looks correctly aligned. Also with a frame size similar to your still looked fine.

About the offset you just have to pass a negative value to `ChartSettings.labelsToAxisSpacingY`. You have to keep in mind that by default the labels are drawn with core graphics on the base view's context and will appear behind everything that is added as subviews - for example the lines and coloured areas. Your semi transparent colours may help with this though. If you need the labels to appear in front you could e.g. make the axis invisible, by not passing it to the chart, and create a layer in which you add labels as UILabels, or maybe also simply create another chart that has only the axis and add it on top of the existing chart, or implement your custom axis :)

**Comment by robomotic** [comment]
Hello the first one worked perfectly.

For the second issue yes, I can see that now they are under the area plot which is transparent but not ideal.
Could you not add some sort of Z order attribute so that in the future people will not have to implement a custom axis or use the UILabels?

Also is there a function to add legends?

**Comment by i-schuetz** [comment]
The z attribute is determined by the index in the layers array. The core graphics option exists due to performance reasons - because of this it draws directly on the context of the chart instead of creating new views and it's impossible to make this appear in front of normal subviews. So, it's like there are 2 parallel stacks in the layers array - on one side layers that use core graphics and on the other layers that use subviews - each respects z order in its own stack but core graphics always appears behind views. It's a bit confusing that they are passed in the same array but is a tradeoff to keep the interface relatively simple (also because each layer can draw both with core graphics and add subviews).

Now the fact that the default axes use core graphics is an implementation detail. If somebody creates an implementation that, for example, also uses core graphics, but on a separate view, such that this will respect the index/z-order in the view-layers, I'm glad to merge it in the library for future use. Also an axis that uses UILabels can be useful - somebody asked recently about this for accessibility. It also makes sense for animations.

Legends are not provided. This is an entirely separate view with its own layout etc. and I didn't see it as a priority to provide it as part of the library. It has also a lot of ways it could be displayed (flow layout, vertical list etc), so I thought the best is people implement this themselves, maybe using a specialised library. Of course it would be nice to provide a default, but I currently don't have time for this.

**Comment by robomotic** [comment]
That makes sense! I am closing this .
