### ISSUE TITLE
time period on the x axis

### ISSUE THREAD

**Issue by marcinwlodarczyk** [i-schuetz/SwiftCharts#97]
Hello,
I have one question regarding the x axis. I would like to present there time periods instead of exact dateTime points - explanation below:

```
with xAxisDates = [Monday, Tuesday, Wednesday, Thursday]
current behaviour of the chart:

               |-------------|-------------|-------------|
            Monday        Tuesday      Wednesday      Thursday


desired behaviour:
               |-------------|-------------|-------------|-------------|
                    Monday       Tuesday      Wednesday     Thursday
```

What is the best way to achieve this with your framework? 

Best,
Marcin

**Comment by i-schuetz** [comment]
For which kind of chart is this?

**Comment by marcinwlodarczyk** [comment]
For scatter and line.

**Comment by i-schuetz** [comment]
Ok, you could hide the default axis (by not passing it to the chart initialiser) and pass a different one which shows the ranges. In this axis the ranges would be normal values. You can use `ChartAxisValueString` similar to [here](https://github.com/i-schuetz/SwiftCharts/blob/master/Examples/Examples/NotNumericExample.swift#L42) for the values - and like in the example also add padding values to the left and right such that the labels appear positioned correctly. (instead of `chartPoints.map{$0.x}` you probably will pass a static array of values, or whatever else source you have for the weekdays).
For the dividers you can either use [ChartPointsViewsLayer](https://github.com/i-schuetz/SwiftCharts/blob/master/SwiftCharts/Layers/ChartPointsViewsLayer.swift) - which is a generic layer that will generate views based on a chart points array (you would pass the dividers positions as chart points) or adjust [ChartDividersLayer](https://github.com/i-schuetz/SwiftCharts/blob/master/SwiftCharts/Layers/ChartDividersLayer.swift) to accept an array of axis values instead of only axes, and pass the corresponding axis values.

**Comment by marcinwlodarczyk** [comment]
Great, your solution works just perfectly!
Thanks a lot for your help and for the great framework (the best I've ever seen for charts).

Cheers,
Marcin

**Comment by i-schuetz** [comment]
Thanks! You were very quick. Glad you could solve it. Seems the generic solution has to wait ;)

**Comment by chandansingh5** [comment]
Hi @marcinwlodarczyk,
I am also facing same issue. how did you resolved it. any help would much appreciated. Thanks

**Comment by marcinwlodarczyk** [comment]
I add two different layers:
1. First that defines the beginning of the time frame, the end and the dividers on the bottom
`Array<NSDate>(startDate.stride(through: endDate.dateByAddingTimeInterval(timeInterval), by: timeInterval))`
where startDate is 00:00 of some day and endDate is 00:00 of the last day

`    static func make(innerFrame innerFrame: CGRect, xAxis: ChartAxisLayer, yAxis: ChartAxisLayer, axis: ChartDividersLayerAxis, linesColor: UIColor, linesWidth: Float, start: Float, end: Float) -> [ChartLayer] {
        let dividersSettings = ChartDividersLayerSettings(linesColor: linesColor, linesWidth: CGFloat(linesWidth), start: CGFloat(start), end: CGFloat(end))
        return [ChartDividersLayer(xAxis: xAxis, yAxis: yAxis, innerFrame: innerFrame, axis: .X, settings: dividersSettings)]
    }`

2. Second that defines labels where the first element is shifted by 12 hours which will give me the label in the middle of the day
`Array<NSDate>(startDate.dateByAddingHours(12).stride(to: endDate, by: timeInterval))`

`    static func make(chartFrame chartFrame: CGRect, yModel: ChartAxisModel, dates: [NSDate], chartSettings: ChartSettings, labelSettings: ChartLabelSettings, xAxisDateFormatter: NSDateFormatter) -> [ChartLayer] {
        let labels = dates.map {
            return ChartAxisValueDate(date: $0, formatter: xAxisDateFormatter, labelSettings: labelSettings)
        }
        let xModelForLabels = ChartAxisModel(axisValues: labels)
        let coordsSpaceForLabels = ChartCoordsSpaceLeftBottomSingleAxis(chartSettings: chartSettings, chartFrame: chartFrame, xModel: xModelForLabels, yModel: yModel)
        return [coordsSpaceForLabels.xAxis]
    }`
